version: 2

models:
  - name: stg_patients
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique

  - name: stg_encounters
    columns:
      - name: encounter_id
        tests:
          - not_null
          - unique
      - name: patient_id
        tests:
          - not_null

  - name: stg_conditions
    columns:
      - name: patient_id
        tests:
          - not_null
      - name: condition_code
        tests:
          - not_null

  - name: stg_observations
    columns:
      - name: patient_id
        tests:
          - not_null
      - name: observation_code
        tests:
          - not_null

  - name: mart_patient_utilization
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique