name: Docker Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-airflow-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t healthcare-airflow .